// Generated by openapi-typescript. Run `pnpm gen:types` to regenerate.
// Placeholder stub until first generation.
export type CursorPage<T> = { items: T[]; next_cursor: string | null }
export interface MeOut { id: string; email: string; role: 'admin' | 'atendente' | 'tecnico'; name: string }
