// Generated by openapi-typescript. Run `pnpm gen:types` to regenerate.
// Placeholder stub until first generation.
export type CursorPage<T> = { items: T[]; next_cursor: string | null }
export interface MeOut { id: string; email: string; role: 'admin' | 'atendente' | 'tecnico'; name: string }

export interface ConversaListItem {
  id: string
  whatsapp: string
  estado: string
  status: string
  cliente_id: string | null
  atendente_id: string | null
  created_at: string
  last_message_at: string | null
}

export interface MensagemOut {
  id: string
  conversa_id: string
  role: 'cliente' | 'bot' | 'atendente'
  content: string | null
  media_type: string | null
  media_url: string | null
  created_at: string
}

export interface ConversaDetail extends ConversaListItem {
  mensagens: MensagemOut[]
}

export interface OsListItem {
  id: string
  codigo: string
  cliente_id: string
  tecnico_id: string | null
  status: string
  problema: string
  endereco: string
  agendamento_at: string | null
  criada_em: string
  concluida_em: string | null
}

export interface OsFoto {
  url: string
  ts: string
  size: number
  mime: string
}

export interface OsOut extends OsListItem {
  fotos: OsFoto[] | null
  csat: number | null
  comentario_cliente: string | null
}

export interface OsCreate {
  cliente_id: string
  problema: string
  endereco: string
  agendamento_at?: string | null
}

export interface OsPatch {
  status?: string | null
  tecnico_id?: string | null
  agendamento_at?: string | null
}

export interface OsConcluirIn {
  csat?: number | null
  comentario?: string | null
}
