// Generated by openapi-typescript. Run `pnpm gen:types` to regenerate.
// Placeholder stub until first generation.
export type CursorPage<T> = { items: T[]; next_cursor: string | null }
export interface MeOut { id: string; email: string; role: 'admin' | 'atendente' | 'tecnico'; name: string }

export interface ConversaListItem {
  id: string
  whatsapp: string
  estado: string
  status: string
  cliente_id: string | null
  atendente_id: string | null
  created_at: string
  last_message_at: string | null
  transferred_at: string | null
  first_response_at: string | null
  tags: string[] | null
  sla_minutes: number
}

export interface MensagemOut {
  id: string
  conversa_id: string
  role: 'cliente' | 'bot' | 'atendente'
  content: string | null
  media_type: string | null
  media_url: string | null
  created_at: string
}

export interface ClienteEmbutido {
  id: string
  nome: string
  cpf_cnpj: string
  whatsapp: string
  plano: string | null
  cidade: string | null
  endereco: string | null
}

export interface ConversaDetail extends ConversaListItem {
  mensagens: MensagemOut[]
  cliente: ClienteEmbutido | null
}

export interface OsListItem {
  id: string
  codigo: string
  cliente_id: string
  tecnico_id: string | null
  status: string
  problema: string
  endereco: string
  agendamento_at: string | null
  criada_em: string
  concluida_em: string | null
  reatribuido_em: string | null
  reatribuido_por: string | null
}

export interface OsFoto {
  url: string
  ts: string
  size: number
  mime: string
}

export interface OsOut extends OsListItem {
  fotos: OsFoto[] | null
  csat: number | null
  comentario_cliente: string | null
  historico_reatribuicoes: Array<{de: string|null, para: string, em: string, por: string}> | null
  follow_up_resposta: string | null
  follow_up_respondido_em: string | null
  follow_up_resultado: string | null
  pppoe_login: string | null
  pppoe_senha: string | null
}

export interface OsCreate {
  cliente_id?: string | null
  tecnico_id: string
  problema: string
  endereco: string
  agendamento_at?: string | null
  pppoe_login?: string | null
  pppoe_senha?: string | null
}

export interface OsReatribuirIn {
  tecnico_id: string
}

export interface OsDeleteOut {
  notif_tecnico: boolean
}

export interface OsPatch {
  status?: string | null
  tecnico_id?: string | null
  agendamento_at?: string | null
}

export interface OsConcluirIn {
  csat?: number | null
  comentario?: string | null
}

// Leads
export interface LeadOut {
  id: string
  nome: string
  whatsapp: string
  interesse: string | null
  status: string
  atendente_id: string | null
  notas: string | null
  created_at: string
  updated_at: string
}
export interface LeadCreate {
  nome: string
  whatsapp: string
  interesse?: string | null
  atendente_id?: string | null
  notas?: string | null
}
export interface LeadPatch {
  nome?: string | null
  interesse?: string | null
  status?: string | null
  atendente_id?: string | null
  notas?: string | null
}

// Clientes
export interface ClienteListItem {
  id: string
  whatsapp: string
  plano: string | null
  status: string | null
  cidade: string | null
  sgp_provider: string | null
  sgp_id: string | null
  created_at: string
  last_seen_at: string | null
}
export interface ClienteDetail extends ClienteListItem {
  nome: string
  cpf_cnpj: string
  endereco: string | null
  retention_until: string | null
}

// Tecnicos
export interface TecnicoListItem {
  id: string
  nome: string
  whatsapp: string | null
  ativo: boolean
  user_id: string | null
  gps_lat: number | null
  gps_lng: number | null
  gps_ts: string | null
}
export interface AreaOut {
  cidade: string
  rua: string
  prioridade: number
}
export interface TecnicoUserOut {
  user_id: string
  email: string
  is_active: boolean
  last_login_at: string | null
}
export interface TecnicoOut extends TecnicoListItem {
  areas: AreaOut[]
  user: TecnicoUserOut | null
}
export interface TecnicoCreate {
  nome: string
  whatsapp?: string | null
  ativo?: boolean
  user_id?: string | null
  email?: string | null
  password?: string | null
}
export interface TecnicoUserCreate {
  email: string
  password: string
}
export interface TecnicoUserResetPassword {
  password: string
}
export interface TecnicoUserPatch {
  is_active?: boolean | null
}
export interface TecnicoPatch {
  nome?: string | null
  whatsapp?: string | null
  ativo?: boolean | null
  gps_lat?: number | null
  gps_lng?: number | null
}
export interface AreaCreate {
  cidade: string
  rua: string
  prioridade?: number
}

// Manutencoes
export interface ManutencaoOut {
  id: string
  titulo: string
  descricao: string | null
  inicio_at: string
  fim_at: string
  cidades: string[] | null
  notificar: boolean
  criada_em: string
}
export interface ManutencaoCreate {
  titulo: string
  descricao?: string | null
  inicio_at: string
  fim_at: string
  cidades?: string[] | null
  notificar?: boolean
}
export interface ManutencaoPatch {
  titulo?: string | null
  descricao?: string | null
  inicio_at?: string | null
  fim_at?: string | null
  cidades?: string[] | null
  notificar?: boolean | null
}

// Config
export interface ConfigOut {
  key: string
  value: unknown
  updated_by: string | null
  updated_at: string
}

// Metricas
export interface MetricasOut {
  conversas_aguardando: number
  conversas_humano: number
  msgs_24h: number
  os_abertas: number
  os_concluidas_24h: number
  csat_avg_30d: number | null
  leads_novos_7d: number
}

export interface SgpClienteOut {
  nome: string
  cpf_cnpj: string
  plano: string | null
  status_contrato: string | null
  cidade: string | null
  endereco: string | null
  cliente_id: string | null
  pppoe_login: string
  pppoe_senha: string
}

export interface RankingTecnicoOut {
  tecnico_id: string
  nome: string
  os_concluidas: number
  csat_avg: number | null
  tempo_medio_min: number | null
  ultima_os_em: string | null
}

// Planos
export interface PlanoIn {
  nome: string
  preco: number
  velocidade: string
  extras: string[]
  descricao: string
  ativo: boolean
  destaque: boolean
}

export interface PlanoOut extends PlanoIn {
  index: number
}
