"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-09 21:31:27.292050

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf_cnpj_encrypted', sa.Text(), nullable=False),
    sa.Column('cpf_hash', sa.String(length=64), nullable=False),
    sa.Column('nome_encrypted', sa.Text(), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('plano', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('endereco_encrypted', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('sgp_provider', sa.Enum('ONDELINE', 'LINKNETAM', name='sgp_provider', native_enum=False), nullable=True),
    sa.Column('sgp_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clientes_cpf_hash', 'clientes', ['cpf_hash'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_clientes_retention', 'clientes', ['retention_until'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_clientes_whatsapp', 'clientes', ['whatsapp'], unique=False)
    op.create_table('manutencoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('inicio_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cidades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notificar', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sgp_cache',
    sa.Column('cpf_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.Enum('ONDELINE', 'LINKNETAM', name='sgp_provider_cache', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cpf_hash', 'provider', name='pk_sgp_cache')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ATENDENTE', 'TECNICO', name='user_role', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_ts', 'audit_log', ['action', 'ts'], unique=False)
    op.create_index('ix_audit_user_ts', 'audit_log', ['user_id', 'ts'], unique=False)
    op.create_table('config',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('conversas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Enum('INICIO', 'AGUARDA_OPCAO', 'LEAD_NOME', 'LEAD_INTERESSE', 'CLIENTE_CPF', 'CLIENTE', 'AGUARDA_ATENDENTE', 'HUMANO', 'ENCERRADA', name='conversa_estado', native_enum=False), nullable=False),
    sa.Column('atendente_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('BOT', 'AGUARDANDO', 'HUMANO', 'ENCERRADA', name='conversa_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atendente_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversas_status_last', 'conversas', ['status', 'last_message_at'], unique=False)
    op.create_index('ix_conversas_whatsapp', 'conversas', ['whatsapp'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('interesse', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NOVO', 'CONTATO', 'CONVERTIDO', 'PERDIDO', name='lead_status', native_enum=False), nullable=False),
    sa.Column('atendente_id', sa.UUID(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atendente_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('VENCIMENTO', 'ATRASO', 'PAGAMENTO', 'OS_CONCLUIDA', name='notificacao_tipo', native_enum=False), nullable=False),
    sa.Column('agendada_para', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ENVIADA', 'FALHA', 'CANCELADA', name='notificacao_status', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tentativas', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_status_due', 'notificacoes', ['status', 'agendada_para'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_expires_active', 'sessions', ['expires_at', 'revoked_at'], unique=False)
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('tecnicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('gps_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tecnicos_user', 'tecnicos', ['user_id'], unique=True)
    op.create_table('llm_eval_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversa_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversa_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('CLIENTE', 'BOT', 'ATENDENTE', name='mensagem_role', native_enum=False), nullable=False),
    sa.Column('content_encrypted', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=40), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_tools_called', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at', name='pk_mensagens'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_mensagens_conversa', 'mensagens', ['conversa_id', 'created_at'], unique=False)
    # Partial unique index on external_id — must include partition key (created_at)
    op.execute("""
        CREATE UNIQUE INDEX ix_mensagens_external
            ON mensagens (external_id, created_at)
            WHERE external_id IS NOT NULL
    """)
    # Initial monthly partitions
    op.execute("""
        CREATE TABLE mensagens_2026_05 PARTITION OF mensagens
        FOR VALUES FROM ('2026-05-01') TO ('2026-06-01')
    """)
    op.execute("""
        CREATE TABLE mensagens_2026_06 PARTITION OF mensagens
        FOR VALUES FROM ('2026-06-01') TO ('2026-07-01')
    """)
    op.create_table('ordens_servico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='os_status', native_enum=False), nullable=False),
    sa.Column('problema', sa.Text(), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('agendamento_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fotos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assinatura', sa.Text(), nullable=True),
    sa.Column('gps_inicio_lat', sa.Float(), nullable=True),
    sa.Column('gps_inicio_lng', sa.Float(), nullable=True),
    sa.Column('gps_fim_lat', sa.Float(), nullable=True),
    sa.Column('gps_fim_lng', sa.Float(), nullable=True),
    sa.Column('csat', sa.SmallInteger(), nullable=True),
    sa.Column('nps', sa.SmallInteger(), nullable=True),
    sa.Column('comentario_cliente', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_os_codigo', 'ordens_servico', ['codigo'], unique=True)
    op.create_index('ix_os_tecnico_status', 'ordens_servico', ['tecnico_id', 'status'], unique=False)
    op.create_table('tecnico_areas',
    sa.Column('tecnico_id', sa.UUID(), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('rua', sa.String(length=120), nullable=False),
    sa.Column('prioridade', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnico_id', 'cidade', 'rua', name='pk_tecnico_areas')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tecnico_areas')
    op.drop_index('ix_os_tecnico_status', table_name='ordens_servico')
    op.drop_index('ix_os_codigo', table_name='ordens_servico')
    op.drop_table('ordens_servico')
    # Drop partitions, manual indexes, then parent mensagens table
    op.execute("DROP TABLE IF EXISTS mensagens_2026_06")
    op.execute("DROP TABLE IF EXISTS mensagens_2026_05")
    op.execute("DROP INDEX IF EXISTS ix_mensagens_external")
    op.execute("DROP INDEX IF EXISTS ix_mensagens_conversa")
    op.execute("DROP TABLE IF EXISTS mensagens CASCADE")
    op.drop_table('llm_eval_samples')
    op.drop_index('ix_tecnicos_user', table_name='tecnicos')
    op.drop_table('tecnicos')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_index('ix_sessions_expires_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_notif_status_due', table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_conversas_whatsapp', table_name='conversas', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_conversas_status_last', table_name='conversas')
    op.drop_table('conversas')
    op.drop_table('config')
    op.drop_index('ix_audit_user_ts', table_name='audit_log')
    op.drop_index('ix_audit_action_ts', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('sgp_cache')
    op.drop_table('manutencoes')
    op.drop_index('ix_clientes_whatsapp', table_name='clientes')
    op.drop_index('ix_clientes_retention', table_name='clientes', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_clientes_cpf_hash', table_name='clientes', postgresql_where='deleted_at IS NULL')
    op.drop_table('clientes')
    # ### end Alembic commands ###
